// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH3iZDXuM3mzJRAWfRlOItsPZXFBO8gcs',
    appId: '1:48215344276:web:c6d3ba9a3e397399bda081',
    messagingSenderId: '48215344276',
    projectId: 'service-system-3b52c',
    authDomain: 'service-system-3b52c.firebaseapp.com',
    storageBucket: 'service-system-3b52c.appspot.com',
    measurementId: 'G-EPS43DY5MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYux2Fzr7yD01ohFk2dJnkclZY-7i4Y8g',
    appId: '1:48215344276:android:b70f9242e3fedc98bda081',
    messagingSenderId: '48215344276',
    projectId: 'service-system-3b52c',
    storageBucket: 'service-system-3b52c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgU_aZyzsSkZ-IM4QTQ9Pji7z7jdmQYCI',
    appId: '1:48215344276:ios:ba68d41d52f8d376bda081',
    messagingSenderId: '48215344276',
    projectId: 'service-system-3b52c',
    storageBucket: 'service-system-3b52c.appspot.com',
    iosClientId: '48215344276-2tpkd3o4fgh5jgp6953bonlmqo2s66m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviceRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgU_aZyzsSkZ-IM4QTQ9Pji7z7jdmQYCI',
    appId: '1:48215344276:ios:ba68d41d52f8d376bda081',
    messagingSenderId: '48215344276',
    projectId: 'service-system-3b52c',
    storageBucket: 'service-system-3b52c.appspot.com',
    iosClientId: '48215344276-2tpkd3o4fgh5jgp6953bonlmqo2s66m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviceRecord',
  );
}
